### ISSUE TITLE
输入长文本没有反应

### ISSUE THREAD

**Issue by kaine380** [xbzstudio/BingAI-Client#13]
https://github.com/kaine380/Mr.-Ranedeer-AI-Tutor
比如这个长关键字的项目，复制进编辑框按发送后没有反应，服务端也没有相应的接口信息反馈

**Comment by viopsa233** [comment]
这个长关键字触发了bing的关键字检测,所以才会没有反应
![网页捕获_19-5-2023_185910_www bing com](https://github.com/xbzstudio/BingAI-Client/assets/118115208/a8df3bd1-1995-4043-9288-2a447991a41f)

**Comment by xbzstudio** [comment]
已经有人回复。故关闭该问题。
