### ISSUE TITLE
端口设置后出些错误，是正确的吗？

### ISSUE THREAD

**Issue by Xingxiwei** [xbzstudio/BingAI-Client#20]
运行完..\run\Install Libs.bat后再打开..\run\run.bat，然后第一个问题天下了false，第二个问题填写了一个9859的端口，回车后，出现以下内容
[32mINFO[0m:     Started server process [[36m14640[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:9859[0m (Press CTRL+C to quit)
我按键盘ctrl和c终止操作后，打开..\static\index，点击左下角的设置，连接服务器改成127.0.0.1:8959，然后再点击回设置，等了10分钟还是loading的

**Comment by xbzstudio** [comment]
你为啥要关掉终端呢？😂

**Comment by xbzstudio** [comment]
关闭此问题，因为没有得到回复
