### ISSUE TITLE
建议发布二进制打包版本，降低使用门槛

### ISSUE THREAD

**Issue by FrozenBicycle** [xbzstudio/BingAI-Client#26]
我基于 1.6.2 稍微改了一点：

- 写死 HOST PORT 为 0.0.0.0:80
- 运行 1 秒后启动默认浏览器打开对话页面
- 更换了默认背景图片

这是我打包的，希望作者采纳：[百度网盘链接](https://pan.baidu.com/s/16HEaoCNTFzErQDvfJ4R7Dw?pwd=1234)

**Comment by xy-cloud-cn** [comment]
头一次在github看到有改动不pr的，还发百度网盘

**Comment by FrozenBicycle** [comment]
> 头一次在github看到有改动不pr的，还发百度网盘

不好意思，平时不怎么用 github，不太懂，好像 issue 也没有撤销按钮？十分抱歉。

**Comment by xbzstudio** [comment]
端口锁80，被别的程序占用，新手就不会搞了呀

**Comment by FrozenBicycle** [comment]
> 端口锁80，被别的程序占用，新手就不会搞了呀

有道理，那就换成 `1145` 端口吧 😉。

然后我简化版的代码就新开一个分支提交上来，应该就不影响了吧。

**Comment by xbzstudio** [comment]
> > 端口锁80，被别的程序占用，新手就不会搞了呀
> 
> 有道理，那就换成 `1145` 端口吧 😉。
> 
> 然后我简化版的代码就新开一个分支提交上来，应该就不影响了吧。

既然这么多人提建议想要锁端口...我在1.7中添加了个配置文件是专门配置端口和是否对外开放的，这样总能满足各位的要求了吧。。

**Comment by xy-cloud-cn** [comment]
为什么不遍历端口自动寻找可用端口，然后自动读写配置文件

**Comment by xy-cloud-cn** [comment]
谁提意见谁pr，我来pr（

**Comment by xy-cloud-cn** [comment]
> 谁提意见谁pr，我来pr（

Modified in #31
