### ISSUE TITLE
最新的1.7版本，无法下载EdgeGPT==0.6.10

### ISSUE THREAD

**Issue by G-LJDS2022** [xbzstudio/BingAI-Client#28]
looking in indexes: http://pypi.douban.com/simpleIRROR: Could not find a version that satisfies the requirement EdgebFT==0.6.10
ERROR: No matching distribution found for EdgeGPT==0.6.10

**Comment by arcmosin** [comment]
> looking in indexes: http://pypi.douban.com/simpleIRROR: Could not find a version that satisfies the requirement EdgebFT==0.6.10 ERROR: No matching distribution found for EdgeGPT==0.6.10

因为你用的douban源，你换python官方源就行了

**Comment by ndcc5** [comment]
> looking in indexes: http://pypi.douban.com/simpleIRROR: Could not find a version that satisfies the requirement EdgebFT==0.6.10 ERROR: No matching distribution found for EdgeGPT==0.6.10

把0.6.10改为0.6.1即可

**Comment by G-LJDS2022** [comment]
怎么换python官方源？

**Comment by jyuan15** [comment]
> 怎么换python官方源？

打开Install Libs.bat，把第一行的 -i http://pypi.douban.com/simple --trusted-host pypi.douban.com 删掉就行了

**Comment by xbzstudio** [comment]
> looking in indexes: http://pypi.douban.com/simpleIRROR: Could not find a version that satisfies the requirement EdgebFT==0.6.10 ERROR: No matching distribution found for EdgeGPT==0.6.10

有人已经回答了这个问题，所以我不再做回答。

不过我有点好奇，为啥我的电脑上能用豆瓣源下载，你的就找不到呢？额。。。

**Comment by G-LJDS2022** [comment]
> 

不知道为什么，开或者不开代理都不行。另外，删掉这行代码后，确实可以正常使用，但是总觉得有点不对劲，感觉只是在忽略错误。

**Comment by xbzstudio** [comment]
已上传最新的bat文件，现在使用官方源下载EdgeGPT 0.6.10，不会再出现该问题。
