### ISSUE TITLE
能否部署在heroku或者 vercel 上

### ISSUE THREAD

**Issue by Nothingness-Void** [xbzstudio/BingAI-Client#3]
如题

**Comment by xbzstudio** [comment]
应该都行。但我没经验。。

**Comment by Nothingness-Void** [comment]
> 应该都行。但我没经验。。

毕竟这俩一个是直接白嫖 另一个是GitHub学生包白送156刀，比自己部署香太多了

**Comment by xbzstudio** [comment]
那确实。部署自己电脑上还得每次都开程序，部署服务器上直接http连过去就行了。

**Comment by xbzstudio** [comment]
PR已合并！谢谢你的支持

**Comment by Nothingness-Void** [comment]
> 那确实。部署自己电脑上还得每次都开程序，部署服务器上直接http连过去就行了。

我看了一眼，貌似不行，vercel仅支持python3.9

**Comment by xbzstudio** [comment]
> > 那确实。部署自己电脑上还得每次都开程序，部署服务器上直接http连过去就行了。
> 
> 我看了一眼，貌似不行，vercel仅支持python3.9

3.9应该也能运行吧，python版本不要太旧就好了，像啥3.5 3.6 3.7的都pass掉，3.9还算比较新的了。

可以试一试用3.9运行，但我不保证在3.9里异步那部分会不会报错。
