### ISSUE TITLE
作者大大能不能出个生成图片的教程

### ISSUE THREAD

**Issue by Xiaoheizi2023** [xbzstudio/BingAI-Client#32]
我每次生成图片都是Loading for New Bing to create images......呜呜呜

**Comment by xbzstudio** [comment]
要搭梯子呀

**Comment by Xiaoheizi2023** [comment]
已经开了代理，后台也没问题，但是网页一直是Loading for New Bing to create images，阿巴阿巴~

**Comment by xbzstudio** [comment]
啊这。。。
