### ISSUE TITLE
chat error http 500

### ISSUE THREAD

**Issue by hfyadr** [xbzstudio/BingAI-Client#33]
一直在http 500，终端里显示Throttled: Request is throttled.

**Comment by xbzstudio** [comment]
我。。我不到啊

**Comment by hfyadr** [comment]
> 我。。我不到啊

我记得昨天还没有问题呢，今天就不行了。我退回1.6版本，也是这种症状。

**Comment by BenoitKAO** [comment]
首先,
感謝大大們開這個Github,
提供超棒的程式碼可以使用~

我當小白鼠幫大家測試過了,

現在是(2023/06/12)

為了避免大家同樣被制裁,
New bing現在已經會偵測BingAI-Clinet,
在BingAI-Clinet不能使用進階問答功能,
"基本"的問答還可以,
沒有提問的次數限制,
但是稍微複雜一點點的問題,
會立刻出現這個錯誤訊息.

如果想問複雜的問題,
建議大家乖乖回去Edge使用New Bing.

但是使用過BingAI-Clinet的帳號,
M$會給予懲罰,
現階段是在24小時內,
帳號會被打回New bing的原始使用者,
只能使用20次提問,
而且似乎也只能使用GPT 3.5,
我比較了我之前的問題,
回答內容有很大的不同.

現在是過了24小時帳號會解禁,
之後不知...

請大家注意和小心!
