### ISSUE TITLE
问一次回答问题很慢，至少要30秒，直接在必应网站上挺快的呀，是我部署的不对吗?

### ISSUE THREAD

**Issue by 123xian123** [xbzstudio/BingAI-Client#49]
是否接受来自别的计算机的请求，我选的false
端口是这个：http://127.0.0.1:65432
跟端口有关吗？跟什么有关啊？
另外打开了梯子后直接就报错了，我还以为要开梯子会快点。
最后一点小建议：增加个回车发送的功能就更好了

**Comment by xbzstudio** [comment]
我前天也遇到了这个问题，回复速度太慢了。但是我并没有对这方面做什么更改，所以我不是很相信这是客户端的问题。。。

另外，其实ctrl+enter可以快捷发送。。。

**Comment by ydrk12** [comment]
附议
