### ISSUE TITLE
手机访问不正常

### ISSUE THREAD

**Issue by jyuan15** [xbzstudio/BingAI-Client#50]
电脑上正常访问，但手机上就一直loading，大家没遇到吗？

![Screenshot_2023-06-06_11-51-54](https://github.com/xbzstudio/BingAI-Client/assets/12642186/9dcb76f9-f792-4c41-aaf0-cb887c036272)

**Comment by xbzstudio** [comment]
在设置里将连接到的服务器，更改为你的电脑的内网ip（加上端口）

**Comment by QAQ3254865169** [comment]
> 在设置里将连接到的服务器，更改为你的电脑的内网ip（加上端口）

照样不可以。。。这样两个端都无法使用
