### ISSUE TITLE
BingAI-Client/config/cookie.json 文件内容空白？？里面不应该有json数据吗？ 这是怎么回事？

### ISSUE THREAD

**Issue by 924950698** [xbzstudio/BingAI-Client#57]
<img width="1445" alt="image" src="https://github.com/xbzstudio/BingAI-Client/assets/33617596/6600b53c-9510-4fa9-ae7a-0b9df4a8f12c">
如题：BingAI-Client/config/cookie.json 文件内容空白？？里面不应该有json数据吗？ 这是怎么回事？

**Comment by xbzstudio** [comment]
难不成我在里边填数据让你盗我的号？
