### ISSUE TITLE
能否docker部署

### ISSUE THREAD

**Issue by H-inXT** [xbzstudio/BingAI-Client#6]

**Comment by xbzstudio** [comment]
没问题

**Comment by dnslin** [comment]
可以贴出对应的docker file 或者说 docker-compose.ymal吗

**Comment by xbzstudio** [comment]
抱歉。。有个不好的消息是。。我不会😹😹😹我只知道docker做什么用的，但是我不会弄docker file。

**Comment by xbzstudio** [comment]
Docker部署已经加啦 是一位友人给我们的项目pr了一个
