### ISSUE TITLE
readme文档里好像有些问题

### ISSUE THREAD

**Issue by springDx** [xbzstudio/BingAI-Client#8]
首先感谢博主的分享！
在教程里让cmd更改cd路径的指令应该是‘cd /d’你的那里好像少了‘/d’，还有博主能不能让webui按回车发送文本啊？如果可以的话就更方便了！

**Comment by xbzstudio** [comment]
有ctrl+enter发送。你可能没发现。另外，文档会更改的，谢谢。🥳
