### ISSUE TITLE
配置了之后，不返还消息啊（无法使用）。

### ISSUE THREAD

**Issue by ddkk3000** [xbzstudio/BingAI-Client#9]
![image](https://github.com/xbzstudio/BingAI-Client/assets/10786234/51542c28-5914-473f-a587-916568e4f525)

**Comment by ddkk3000** [comment]
发送消息后，bing不回复

**Comment by xbzstudio** [comment]
你。。。。打开聊天页面里的设置，把连接到的服务器设置为127.0.0.1:8234

**Comment by ddkk3000** [comment]
这不行的。仍然无法返回回复的。我用你们官方的演示网站也不行的。


报错信息如下


ERROR:&nbsp; &nbsp; Exception in ASGI application
Traceback (most recent call last):
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
&nbsp; &nbsp; result = await app(&nbsp; # type: ignore[func-returns-value]
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
&nbsp; &nbsp; return await self.app(scope, receive, send)
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\applications.py", line 274, in __call__
&nbsp; &nbsp; await super().__call__(scope, receive, send)
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\applications.py", line 118, in __call__
&nbsp; &nbsp; await self.middleware_stack(scope, receive, send)
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
&nbsp; &nbsp; raise exc
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
&nbsp; &nbsp; await self.app(scope, receive, _send)
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
&nbsp; &nbsp; await self.simple_response(scope, receive, send, request_headers=headers)
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
&nbsp; &nbsp; await self.app(scope, receive, send)
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
&nbsp; &nbsp; raise exc
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
&nbsp; &nbsp; await self.app(scope, receive, sender)
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
&nbsp; &nbsp; raise e
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
&nbsp; &nbsp; await self.app(scope, receive, send)
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 706, in __call__
&nbsp; &nbsp; await route.handle(scope, receive, send)
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 276, in handle
&nbsp; &nbsp; await self.app(scope, receive, send)
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 66, in app
&nbsp; &nbsp; response = await func(request)
&nbsp; File "C:\BingAI-Client-BingAI-Client1.5.2\bingserver.py", line 235, in api
&nbsp; &nbsp; token, chatBot = getChatBot(token)
&nbsp; File "C:\BingAI-Client-BingAI-Client1.5.2\bingserver.py", line 53, in getChatBot
&nbsp; &nbsp; chatBot = EdgeGPT.Chatbot(proxy=PROXY, cookie_path=COOKIE_FILE_PATH)
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 606, in __init__
&nbsp; &nbsp; _Conversation(self.cookies, self.proxy),
&nbsp; File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python310\lib\site-packages\EdgeGPT.py", line 344, in __init__
&nbsp; &nbsp; raise NotAllowedToAccess(self.struct["result"]["message"])
EdgeGPT.NotAllowedToAccess: Sorry, you need to login first to access this service.

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, May 16, 2023 08:08 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [xbzstudio/BingAI-Client] 配置了之后，不返还消息啊（无法使用）。 (Issue #9)

&nbsp;



 
你。。。。打开聊天页面里的设置，把连接到的服务器设置为127.0.0.1:8234

**Comment by xbzstudio** [comment]
edgegpt说你没登录。你没填cookie还是填错cookie？

**Comment by wg961** [comment]
可能是还不能用newbing吧，我是注册一天以后才给我发了邮件，重新更新一下cookie就好了

**Comment by wg961** [comment]
@xbzstudio 
为什么一段时间挂着后再使用，new bing将不会回复内容

**Comment by xbzstudio** [comment]
> @xbzstudio 为什么一段时间挂着后再使用，new bing将不会回复内容

正常现象。太长时间不提问会丢失token。试着按下“新主题”按钮，用记忆系统解决这个问题。
